services:
  - type: web
    name: gestion-salud-osea
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn GestionSaludOsea.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db-salud-osea
          property: connectionString

databases:
  - name: db-salud-osea
    plan: free
    region: oregon
